### ISSUE TITLE
Update linked iframe URL 

### ISSUE THREAD

**Issue by mooomooo** [edemaine/comingle#114]
If you have added a webpage iframe (e.g. Wikipedia) to a room, and you follow some links within there to a more appropriate webpage, it would be nice to have a button on that frame that can update everyone's frame to the page you're currently viewing.  

Additionally (or alternately) maybe a way to pop-out a link from a current frame into a new frame?

**Comment by edemaine** [comment]
Sadly, that is not possible (without some proxy magic). Comingle cannot look inside the iframe, even to know what it's current location/URL is.
