### ISSUE TITLE
Import into Cocreate

### ISSUE THREAD

**Issue by mooomooo** [edemaine/comingle#115]
Once https://github.com/edemaine/cocreate/issues/22 gets implemented, it would be useful to have a way of importing from a webpage iframe into a Cocreate board, either by taking a screenshot of the currently visible section of the page, or selecting an image or pdf from the page and sending it to the whiteboard to collaboratively mark it up.  

Perhaps an alternate solution could be to give the whiteboard a transparent background and overlay it on the webpage, but then there would need to be some way of synchronizing scrolling and zoom between the board and the background webpage.

**Comment by edemaine** [comment]
Taking screenshots of iframes, aligning scroll, and aligning zooms are all impossible, I'm afraid. (without some proxy magic)

But you could always use the operating-system screenshot functionality and paste into Cocreate.
