### ISSUE TITLE
Status of https://comingle.csail.mit.edu/?

### ISSUE THREAD

**Issue by cpitclaudel** [edemaine/comingle#146]
Hi there,

We're looking for a platform to use for office hours of 6.822 and there was great feedback about comingle in the UA remote teaching guide.  What is the status of https://comingle.csail.mit.edu/ ?  Is it supported, or is it a test server?  Are there moderation tools that the meeting creator can use (to delete messages, or to kick out an unwanted participant, etc?)

On the security front: I've noticed that some meetings on comingle.csail.mit.edu are publicly indexed by Google; should that be turned off?  Is there a way to authenticate participants? I'm worried about zoom-bombing type incidents.

Do Jitsi meetings use the free tier? (That is, would we be freeloading on Jitsi's infrastructure?)

**Comment by edemaine** [comment]
This would be better discussed in email. Please email me at edemaine@mit.edu

**Comment by cpitclaudel** [comment]
Thanks!  Just sent you an email :)
