### ISSUE TITLE
Reload tabs

### ISSUE THREAD

**Issue by edemaine** [edemaine/comingle#28]
Reloading a tab is possible by right clicking on the frame and selecting "Reload Frame" (on Chrome anyway). But it'd be nice to have this as a feature of Comingle, to reset a single tab without having to reload the entire page. Options:
* A reload button on every tab. Might be a bit of a waste of space.
* A reload button for tabset, to reload the current tab. I think this makes the most sense; we only care about the currently displayed tab.

**Comment by diomidov** [comment]
Another option:
* A reload button on every active tab.
