### ISSUE TITLE
Preserve Jitsi state when going room to room

### ISSUE THREAD

**Issue by edemaine** [edemaine/comingle#76]
We'd like all the Jitsi tabs to feel like a single "meeting" whose state is preserved when jumping from room to room.

* [x] Mute/unmute
* [x] Video/no video
* [ ] Background blurred
* [ ] Connected/disconnected? (#191)
* [ ] Tiled view of others' video?

We can choose the start state for mute and video via `startWithAudioMuted` and `startWithVideoMuted` (see [config.js](https://github.com/jitsi/jitsi-meet/blob/master/config.js)). We want to look for events `audioMuteStatusChanged` and `videoMuteStatusChanged` as defined [here](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe).

[Here's one approach to using the official Jitsi API in React](https://dev.to/metamodal/add-jitsi-meet-to-your-react-app-33j9). I don't think we can use this as-is, because it doesn't properly handle when there are multiple Jitsi widgets being made at the same time (whereas `client/lib/Markdown.coffee` does).

**Comment by diomidov** [comment]
It's really annoying that when I join a room Jitsi uses my mute state from the last time I was in that room.

**Comment by edemaine** [comment]
Ah, is that what it's doing? I agree. Do you want to try to implement this? We need to figure out the `postMessage` protocol and speak it.

**Comment by diomidov** [comment]
I'll look into it. Maybe we should switch to the official Jitsi API ;-)

**Comment by edemaine** [comment]
FYI, I just (finally) switched to using the official Jitsi API, so this and #191 should be much easier to implement now. Mainly I need to figure out how/when to pass state from one Jitsi tab to another Jitsi tab in another room...

**Comment by edemaine** [comment]
* Implemented mute status preservation.
* Background blurred state seems inaccessible.
* Tile view seems questionable (different rooms have different numbers of people, so may have different preferences).
* Connected/disconnected state replaced by #191
