### ISSUE TITLE
Deleting rooms

### ISSUE THREAD

**Issue by hanryhu** [edemaine/comingle#89]
Hello, we are planning to use a single Comingle link for the whole semester.

- Is this advisable?
- If so, is there a way to truly delete rooms, or can we only archive them?  We would like to spontaneously create rooms, but don't want to deal with accumulated junk rooms throughout the semester.

Thanks!

**Comment by edemaine** [comment]
A single link for the whole semester is my plan as well. Of course, this is the first semester we're trying it, so we'll see how it goes...

There currently isn't a way to permanently delete rooms, only archive. (If you're running your own server, you could do it with manual database operations.) I might add this once we have authentication, but I don't view it as a priority. Perhaps you could give your motivation for permanent deletion?

**Comment by hanryhu** [comment]
> Perhaps you could give your motivation for permanent deletion?

I was going to say it looks cluttered and hinders access to the Create Room button, but then I realized the list can be collapsed from the top, so it looks like that's a good workaround for now.  Thanks for the explanation

**Comment by edemaine** [comment]
Yeah, the archived rooms are actually collapsed by default. A user has to intentionally go digging there if they want an old room. (The motivation is that a student might want to revisit an old topic, including its state. Also to enable staff to recover an accidentally archived room.)

Also, the Create Room button is always visible, even if a lot of rooms are showing.

**Comment by edemaine** [comment]
@hanryhu Admins can now delete rooms and tabs! Send me email if you need the meeting secret for your existing meeting.
